# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

name: $(masterPackageVersion)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\**\Relativity.Test.Helpers.NUnit.Integration.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'
    distributionBatchType: basedOnAssembly
    runSettingsFile: 'Source\Relativity.Test.Helpers\Relativity.Test.Helpers.NUnit.Integration\test.runsettings'
    overrideTestrunParameters: 
      -TestWorkspaceName $(testWorkspaceName)
      -TestWorkspaceTemplateName $(testWorkspaceTemplateName)
      -AdminUsername $(adminUsername)
      -AdminPassword $(adminPassword)
      -SQLUserName $(sqlUserName)
      -SQLPassword $(sqlPassword)
      -SQLServerAddress $(sqlServerAddress)
      -RSAPIServerAddress $(rsapiServerAddress)
      -RESTServerAddress $(restServerAddress)
      -ServerBindingType $(serverBindingType)
      -RelativityInstanceAddress $(relativityInstanceAddress)
      -ForceDbContext $(forceDbContext)
      -GmailMailTestEmailAddress $(gmailMailTestEmailAddress)
      -GmailMailTestEmailPassword $(gmailMailTestEmailPassword)
      -MailTrapTestApiKey $(mailTrapTestApiKey)
      -MailTrapTestEmailAddress $(mailTrapTestEmailAddress)
      -MailTrapTestEmailUsername $(mailTrapTestEmailUsername)
      -MailTrapTestEmailPassword $(mailTrapTestEmailPassword)

# - task: NuGetCommand@2
#   inputs:
#     command: 'pack'
#     feedsToUse: 'select'
#     packagesToPack: '**/*.nuspec'
#     versioningScheme: byBuildNumber
#   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

# - task: NuGetCommand@2
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'relativityDevNuget'
#   condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
